
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(70, 10, 191, 221))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 130, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(50, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(self.page_2)
        self.radioButton.setGeometry(QtCore.QRect(10, 110, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.page_2)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.page_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 71, 16))
        self.label_3.setObjectName("label_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_4.setGeometry(QtCore.QRect(40, 60, 82, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_5.setGeometry(QtCore.QRect(40, 90, 82, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_6.setGeometry(QtCore.QRect(50, 130, 82, 17))
        self.radioButton_6.setObjectName("radioButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 170, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 170, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(60, 20, 47, 13))
        self.label_4.setObjectName("label_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_7.setGeometry(QtCore.QRect(30, 40, 82, 17))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_8.setGeometry(QtCore.QRect(30, 70, 82, 17))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.page_4)
        self.radioButton_9.setGeometry(QtCore.QRect(40, 120, 82, 17))
        self.radioButton_9.setObjectName("radioButton_9")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_5 = QtWidgets.QLabel(self.page_5)
        self.label_5.setGeometry(QtCore.QRect(60, 20, 47, 13))
        self.label_5.setObjectName("label_5")
        self.radioButton_10 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_10.setGeometry(QtCore.QRect(30, 40, 82, 17))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_11.setGeometry(QtCore.QRect(50, 100, 82, 17))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.page_5)
        self.radioButton_12.setGeometry(QtCore.QRect(70, 120, 82, 17))
        self.radioButton_12.setObjectName("radioButton_12")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 170, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_6 = QtWidgets.QLabel(self.page_6)
        self.label_6.setGeometry(QtCore.QRect(40, 20, 47, 13))
        self.label_6.setObjectName("label_6")
        self.radioButton_13 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_13.setGeometry(QtCore.QRect(30, 50, 82, 17))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_14.setGeometry(QtCore.QRect(30, 80, 82, 17))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.page_6)
        self.radioButton_15.setGeometry(QtCore.QRect(100, 60, 82, 17))
        self.radioButton_15.setObjectName("radioButton_15")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 150, 131, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_7 = QtWidgets.QLabel(self.page_7)
        self.label_7.setGeometry(QtCore.QRect(60, 30, 101, 16))
        self.label_7.setObjectName("label_7")
        self.radioButton_16 = QtWidgets.QRadioButton(self.page_7)
        self.radioButton_16.setGeometry(QtCore.QRect(50, 70, 82, 17))
        self.radioButton_16.setObjectName("radioButton_16")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 140, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_8 = QtWidgets.QLabel(self.page_8)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 131, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_8)
        self.label_9.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label_9.setObjectName("label_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_8)
        self.pushButton_8.setGeometry(QtCore.QRect(50, 150, 131, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.stackedWidget.addWidget(self.page_8)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "test"))
        self.pushButton_2.setText(_translate("Form", "nachat "))
        self.pushButton.setText(_translate("Form", "ghjljk;bnmn"))
        self.radioButton.setText(_translate("Form", "chelovek"))
        self.radioButton_2.setText(_translate("Form", "loh"))
        self.radioButton_3.setText(_translate("Form", "adekvat"))
        self.label_2.setText(_translate("Form", "maksim kto"))
        self.label_3.setText(_translate("Form", "maksim kto"))
        self.radioButton_4.setText(_translate("Form", "debil"))
        self.radioButton_5.setText(_translate("Form", "muzhik"))
        self.radioButton_6.setText(_translate("Form", "vsem privet"))
        self.pushButton_3.setText(_translate("Form", "ghjlkl;bnm"))
        self.pushButton_4.setText(_translate("Form", "ghjlk;bnm"))
        self.label_4.setText(_translate("Form", "privet"))
        self.radioButton_7.setText(_translate("Form", "privet"))
        self.radioButton_8.setText(_translate("Form", "poka"))
        self.radioButton_9.setText(_translate("Form", "\';lpokjh"))
        self.label_5.setText(_translate("Form", "yarick loh "))
        self.radioButton_10.setText(_translate("Form", "net"))
        self.radioButton_11.setText(_translate("Form", "net tipo"))
        self.radioButton_12.setText(_translate("Form", "tupo.net"))
        self.pushButton_5.setText(_translate("Form", "next question"))
        self.label_6.setText(_translate("Form", "kak dela"))
        self.radioButton_13.setText(_translate("Form", "norm"))
        self.radioButton_14.setText(_translate("Form", "ploho"))
        self.radioButton_15.setText(_translate("Form", "greusoto"))
        self.pushButton_6.setText(_translate("Form", "sleduyshiy boprtools"))
        self.label_7.setText(_translate("Form", "ip 24 26 b kto?"))
        self.radioButton_16.setText(_translate("Form", "vonuchki"))
        self.pushButton_7.setText(_translate("Form", "koneec"))
        self.label_8.setText(_translate("Form", "tvoi balli : "))
        self.label_9.setText(_translate("Form", "ocenka:"))
        self.pushButton_8.setText(_translate("Form", "poshiartartfr6t7uyfvo"))
